# Generated by Django 3.0.6 on 2020-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planety', '0002_auto_20200603_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_posts'),
        ),
    ]
